# Generated by Django 5.2.8 on 2025-11-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=150, verbose_name='اسم المتجر')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='شعار المتجر')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني للتواصل')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='العنوان')),
                ('about_text', models.TextField(blank=True, verbose_name='عن المتجر')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعداد الموقع',
                'verbose_name_plural': 'إعدادات الموقع',
            },
        ),
    ]
